services:
  backend:
    build: ./backend
    container_name: flask-api
    expose:
      - 5000

  frontend:
    build: ./frontend
    container_name: node-frontend
    expose:
      - 3000

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
