services:
  backend:
    image: hackitect7/flask-api:latest
    ports:
      - "5000:5000"

  frontend:
    image: hackitect7/node-frontend:latest
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
